# Generated by Django 2.1 on 2020-03-13 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.CharField(max_length=512, verbose_name='内容')),
                ('status', models.IntegerField(choices=[(0, '审核中'), (1, '已通过')], default=0, verbose_name='状态')),
                ('answerer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='回答者')),
                ('attach_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.Answer', verbose_name='从属于')),
            ],
            options={
                'verbose_name': '答案',
                'verbose_name_plural': '答案',
                'db_table': 'delivery_answer',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.CharField(max_length=512, verbose_name='内容')),
                ('read_count', models.IntegerField(default=0, verbose_name='阅读量')),
                ('status', models.IntegerField(choices=[(0, '审核中'), (1, '已通过')], default=0, verbose_name='状态')),
                ('questioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='提问人')),
            ],
            options={
                'verbose_name': '问题',
                'verbose_name_plural': '问题',
                'db_table': 'delivery_question',
            },
        ),
        migrations.CreateModel(
            name='StoreHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('province', models.CharField(max_length=16, verbose_name='所属省份')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('house_code', models.CharField(max_length=8, unique=True, verbose_name='仓库编码')),
                ('arrived', models.CharField(max_length=512, verbose_name='到达站')),
                ('premium', models.CharField(max_length=512, verbose_name='升贴水')),
                ('address', models.CharField(max_length=512, verbose_name='地址')),
                ('link', models.CharField(max_length=256, verbose_name='联系人')),
                ('tel_phone', models.CharField(max_length=512, verbose_name='联系电话')),
                ('fax', models.CharField(max_length=64, verbose_name='传真')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('variety', models.ManyToManyField(to='basic.Variety', verbose_name='品种')),
            ],
            options={
                'verbose_name': '交割仓库',
                'verbose_name_plural': '交割仓库',
                'db_table': 'delivery_storehouse',
            },
        ),
        migrations.CreateModel(
            name='VarietyInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('delivery_date', models.CharField(blank=True, max_length=64, null=True, verbose_name='最后交易日')),
                ('warrant_expire_date', models.CharField(blank=True, max_length=512, null=True, verbose_name='仓单有效期')),
                ('delivery_unit_min', models.CharField(blank=True, max_length=64, null=True, verbose_name='最小交割单位')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='basic.Variety', verbose_name='品种')),
            ],
            options={
                'verbose_name': '品种基本信息',
                'verbose_name_plural': '品种基本信息',
                'db_table': 'delivery_variety_info',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Question', verbose_name='问题'),
        ),
    ]
