# Generated by Django 2.1 on 2020-03-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('en_code', models.CharField(max_length=32, verbose_name='英文代称')),
                ('exchange', models.SmallIntegerField(choices=[(1, '郑州商品交易所'), (2, '上海期货交易所'), (3, '大连商品交易所'), (4, '中国金融期货交易所'), (5, '上海国际能源交易中心')], default=0, verbose_name='从属于')),
            ],
            options={
                'verbose_name': '服务指引',
                'verbose_name_plural': '服务指引',
                'db_table': 'delivery_service_guide',
            },
        ),
    ]
