# Generated by Django 2.1 on 2020-03-04 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20200304_1638'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answer',
            table='delivery_answer',
        ),
        migrations.AlterModelTable(
            name='question',
            table='delivery_question',
        ),
    ]
