# Generated by Django 2.1 on 2020-03-06 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_auto_20200304_1528'),
        ('delivery', '0004_storehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarietyInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('delivery_date', models.CharField(blank=True, max_length=64, null=True, verbose_name='最后交易日')),
                ('warrant_expire_date', models.CharField(blank=True, max_length=512, null=True, verbose_name='仓单有效期')),
                ('delivery_unit_min', models.CharField(blank=True, max_length=64, null=True, verbose_name='最小交割单位')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Variety', verbose_name='品种')),
            ],
            options={
                'verbose_name': '品种基本信息',
                'verbose_name_plural': '品种基本信息',
                'db_table': 'delivery_variety_info',
            },
        ),
    ]
