# Generated by Django 2.1 on 2019-12-19 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic', '0002_auto_20191212_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=256, verbose_name='名称')),
                ('sql_name', models.CharField(max_length=32, verbose_name='数据库中表名称')),
            ],
            options={
                'verbose_name': '数据表名',
                'verbose_name_plural': '数据表名',
                'db_table': 'trend_table',
            },
        ),
        migrations.CreateModel(
            name='TrendTableGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='组名')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_table_groups', to='basic.Variety', verbose_name='所属品种')),
            ],
            options={
                'verbose_name': '数据表组别',
                'verbose_name_plural': '数据表组别',
                'db_table': 'trend_table_group',
            },
        ),
        migrations.AddField(
            model_name='trendtable',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='trend.TrendTableGroup', verbose_name='所属组别'),
        ),
        migrations.AlterUniqueTogether(
            name='trendtablegroup',
            unique_together={('name', 'variety')},
        ),
        migrations.AlterUniqueTogether(
            name='trendtable',
            unique_together={('name', 'group')},
        ),
    ]
