# Generated by Django 2.1 on 2020-03-13 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=256, verbose_name='名称')),
                ('sql_name', models.CharField(max_length=32, verbose_name='数据库中表名称')),
                ('origin_note', models.CharField(blank=True, max_length=512, null=True, verbose_name='数据来源')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_trend_tables', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_trend_tables', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '数据表名',
                'verbose_name_plural': '数据表名',
                'db_table': 'trend_table',
            },
        ),
        migrations.CreateModel(
            name='TrendTableGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='组名')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_table_groups', to='basic.Variety', verbose_name='所属品种')),
            ],
            options={
                'verbose_name': '数据表组别',
                'verbose_name_plural': '数据表组别',
                'db_table': 'trend_table_group',
            },
        ),
        migrations.CreateModel(
            name='VarietyChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='图表名')),
                ('category', models.CharField(choices=[('line', '折线图'), ('bar', '柱形图'), ('double_line', '双轴折线图'), ('double_bar', '双轴柱形图')], max_length=32, verbose_name='图表类型')),
                ('x_bottom', models.CharField(max_length=16, verbose_name='x轴')),
                ('x_top', models.CharField(blank=True, max_length=16, null=True, verbose_name='上x轴')),
                ('y_left', models.CharField(max_length=32, verbose_name='左轴')),
                ('y_right', models.CharField(blank=True, max_length=32, null=True, verbose_name='右轴')),
                ('x_bottom_label', models.CharField(blank=True, max_length=32, null=True, verbose_name='x轴名称')),
                ('x_top_label', models.CharField(blank=True, max_length=32, null=True, verbose_name='上x轴名称')),
                ('y_left_label', models.CharField(blank=True, max_length=32, null=True, verbose_name='y轴名称')),
                ('y_right_label', models.CharField(blank=True, max_length=32, null=True, verbose_name='右y轴名称')),
                ('start', models.CharField(blank=True, max_length=32, null=True, verbose_name='起始')),
                ('end', models.CharField(blank=True, max_length=32, null=True, verbose_name='终止')),
                ('is_top', models.BooleanField(default=False, verbose_name='主页展示')),
                ('is_show', models.BooleanField(default=False, verbose_name='品种展示')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_charts', to='trend.TrendTable', verbose_name='数据表')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='basic.Variety', verbose_name='所属品种')),
            ],
            options={
                'verbose_name': '品种图表',
                'verbose_name_plural': '品种图表',
                'db_table': 'trend_variety_chart',
            },
        ),
        migrations.AddField(
            model_name='trendtable',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='trend.TrendTableGroup', verbose_name='所属组别'),
        ),
        migrations.AlterUniqueTogether(
            name='varietychart',
            unique_together={('name', 'variety')},
        ),
        migrations.AlterUniqueTogether(
            name='trendtablegroup',
            unique_together={('name', 'variety')},
        ),
    ]
