# Generated by Django 2.1 on 2020-02-04 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trendtable',
            unique_together=set(),
        ),
    ]
