# Generated by Django 2.1 on 2020-01-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendtable',
            name='origin_note',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='数据来源'),
        ),
    ]
