# Generated by Django 2.1 on 2019-12-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0002_auto_20191219_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendtable',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='已删除'),
        ),
    ]
