# Generated by Django 2.1 on 2019-12-25 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic', '0002_auto_20191212_1127'),
        ('trend', '0003_trendtable_is_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarietyChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='图表名')),
                ('category', models.CharField(choices=[('line', '折线图'), ('bar', '柱形图'), ('double_line', '双轴折线图'), ('double_bar', '双轴柱形图')], max_length=32, verbose_name='图表类型')),
                ('x_bottom', models.CharField(max_length=16, verbose_name='x轴')),
                ('x_top', models.CharField(blank=True, max_length=16, null=True, verbose_name='上x轴')),
                ('y_left', models.CharField(max_length=32, verbose_name='左轴')),
                ('y_right', models.CharField(blank=True, max_length=32, null=True, verbose_name='右轴')),
                ('x_bottom_label', models.CharField(blank=True, max_length=32, null=True, verbose_name='x轴名称')),
                ('x_top_label', models.CharField(blank=True, max_length=32, null=True, verbose_name='上x轴名称')),
                ('y_left_label', models.CharField(blank=True, max_length=32, null=True, verbose_name='y轴名称')),
                ('x_right_label', models.CharField(blank=True, max_length=32, null=True, verbose_name='右y轴名称')),
                ('start', models.CharField(blank=True, max_length=32, null=True, verbose_name='起始')),
                ('end', models.CharField(blank=True, max_length=32, null=True, verbose_name='终止')),
                ('is_top', models.BooleanField(default=False, verbose_name='主页展示')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_charts', to='trend.TrendTable', verbose_name='数据表')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='basic.Variety', verbose_name='所属品种')),
            ],
            options={
                'verbose_name': '品种图表',
                'verbose_name_plural': '品种图表',
                'db_table': 'trend_variety_chart',
            },
        ),
        migrations.AlterUniqueTogether(
            name='varietychart',
            unique_together={('name', 'variety')},
        ),
    ]
