# Generated by Django 2.1 on 2019-12-25 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0004_auto_20191225_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='varietychart',
            old_name='x_right_label',
            new_name='y_right_label',
        ),
    ]
