# Generated by Django 2.1 on 2019-12-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0005_auto_20191225_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='varietychart',
            name='is_show',
            field=models.BooleanField(default=False, verbose_name='品种展示'),
        ),
    ]
