# Generated by Django 2.1 on 2019-12-30 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0006_varietychart_is_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendtable',
            name='is_delete',
        ),
    ]
