# Generated by Django 2.1 on 2020-02-04 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalreport',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normal_reports', to='home.DataCategory', verbose_name='所属分类'),
        ),
        migrations.AlterField(
            model_name='normalreport',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_files', to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
        migrations.AlterField(
            model_name='transactionnotice',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_notice', to='home.DataCategory', verbose_name='所属分类'),
        ),
        migrations.AlterField(
            model_name='transactionnotice',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notice_files', to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
    ]
