# Generated by Django 2.1 on 2019-12-16 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=64, verbose_name='标题')),
                ('image', models.FileField(upload_to='home/advertisement/image/', verbose_name='图片')),
                ('file', models.FileField(blank=True, upload_to='home/advertisement/', verbose_name='文件')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '首页广告',
                'verbose_name_plural': '首页广告',
                'db_table': 'home_advertisement',
            },
        ),
    ]
