# Generated by Django 2.1 on 2019-12-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=16, verbose_name='名称')),
                ('group', models.CharField(choices=[('normal_report', '常规报告'), ('transaction_notice', '交易通知')], max_length=32, verbose_name='组别')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'db_table': 'home_data_category',
            },
        ),
        migrations.AlterUniqueTogether(
            name='datacategory',
            unique_together={('name', 'group')},
        ),
    ]
