# Generated by Django 2.1 on 2019-12-18 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_auto_20191217_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=256, verbose_name='文件名')),
                ('file', models.FileField(upload_to='home/transactionNotice/%Y/%m/%d/')),
                ('date', models.DateField(verbose_name='通知日期')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_notice', to='home.DataCategory', verbose_name='所属分类')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notice_files', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '交易通知',
                'verbose_name_plural': '交易通知',
                'db_table': 'home_transaction_notice',
            },
        ),
        migrations.AlterUniqueTogether(
            name='transactionnotice',
            unique_together={('name', 'date')},
        ),
    ]
