# Generated by Django 2.1 on 2019-12-18 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_auto_20191218_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotCommodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('area', models.CharField(max_length=128, verbose_name='地区')),
                ('level', models.CharField(max_length=16, verbose_name='等级')),
                ('price', models.FloatField(verbose_name='价格')),
                ('increase', models.FloatField(verbose_name='增减')),
                ('date', models.DateField(verbose_name='日期')),
                ('note', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '现货报表',
                'db_table': 'home_spot_commodity',
            },
        ),
        migrations.AlterUniqueTogether(
            name='spotcommodity',
            unique_together={('name', 'date')},
        ),
    ]
