# Generated by Django 2.1 on 2019-12-18 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_auto_20191218_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('date', models.DateField(verbose_name='日期')),
                ('time', models.TimeField(verbose_name='时间')),
                ('country', models.CharField(max_length=128, verbose_name='地区')),
                ('event', models.TextField(verbose_name='事件')),
                ('expected', models.CharField(max_length=64, verbose_name='预期值')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '财经日历',
                'db_table': 'home_finance_calendar',
            },
        ),
        migrations.AlterUniqueTogether(
            name='financecalendar',
            unique_together={('date', 'country', 'event')},
        ),
    ]
