# Generated by Django 2.1 on 2019-12-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='名称备注')),
                ('machine_code', models.CharField(max_length=32, unique=True, verbose_name='机器识别码')),
                ('is_manager', models.BooleanField(default=False, verbose_name='管理端')),
                ('is_active', models.BooleanField(default=True, verbose_name='有效')),
            ],
            options={
                'verbose_name': '客户端',
                'verbose_name_plural': '客户端',
                'db_table': 'basic_client',
            },
        ),
    ]
