# Generated by Django 2.1 on 2020-01-17 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOpenRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Client', verbose_name='客户端')),
            ],
            options={
                'verbose_name': '客户端打开记录',
                'verbose_name_plural': '客户端打开记录',
                'db_table': 'basic_client_opened',
            },
        ),
        migrations.CreateModel(
            name='ModuleOpenRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Client', verbose_name='客户端')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Module', verbose_name='模块')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '模块访问记录',
                'verbose_name_plural': '模块访问记录',
                'db_table': 'basic_module_opened',
            },
        ),
    ]
