# Generated by Django 2.1 on 2020-03-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_variety_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variety',
            name='exchange',
            field=models.SmallIntegerField(choices=[(1, '郑州商品交易所'), (2, '上海期货交易所'), (3, '大连商品交易所'), (4, '中国金融期货交易所'), (5, '上海国际能源交易中心')], default=0, verbose_name='交易所'),
        ),
    ]
