# Generated by Django 2.1 on 2019-12-11 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoclient',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(3000, 1, 1, 0, 0), verbose_name='失效时间'),
        ),
        migrations.AlterField(
            model_name='usertomodule',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(3000, 1, 1, 0, 0), verbose_name='失效时间'),
        ),
    ]
