# Generated by Django 2.1 on 2019-12-27 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='组名')),
            ],
            options={
                'verbose_name': '服务组别',
                'verbose_name_plural': '服务组别',
                'db_table': 'info_group',
            },
        ),
        migrations.CreateModel(
            name='InfoService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='组名')),
                ('is_active', models.BooleanField(default=True, verbose_name='有效')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_service.InfoGroup', verbose_name='服务内容')),
            ],
            options={
                'verbose_name': '服务内容',
                'verbose_name_plural': '服务内容',
                'db_table': 'info_service',
            },
        ),
    ]
