# Generated by Django 2.1 on 2019-12-30 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=256, verbose_name='名称')),
                ('file', models.FileField(upload_to='info/marketAly/%Y/%m/%d/')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '市场分析',
                'verbose_name_plural': '市场分析',
                'db_table': 'info_market_analysis',
            },
        ),
    ]
