# Generated by Django 2.1 on 2019-12-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_service', '0002_auto_20191227_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoservice',
            name='group',
        ),
        migrations.DeleteModel(
            name='InfoGroup',
        ),
        migrations.DeleteModel(
            name='InfoService',
        ),
    ]
